### ISSUE TITLE
allow to reflect not required properties in interface

### ISSUE THREAD

**Issue by stepancar** [pcan/reflec-ts-examples#2]
opent your inspect-interface example and then mark any prop as not require using '?' typescript keyword and then run, compile, see runtime example.

**Comment by stepancar** [comment]
I'm sory, this issue for reflect-ts

**Comment by pcan** [comment]
I'm adding another property to `Member` in order to mark optional fields.

**Comment by pcan** [comment]
Related issue: https://github.com/pcan/reflec-ts/issues/8

**Comment by pcan** [comment]
Published 0.3.5 version on npm :tada:

**Comment by stepancar** [comment]
@pcan  thank you! I will check tomorrow
