### ISSUE TITLE
Is it possible to detect if class implements empty interface?

### ISSUE THREAD

**Issue by bbonczek** [pcan/reflec-ts-examples#4]
Title is pretty self-explanatory. Below i put some sample code, to illustrate what i mean:

```
export interface IFoo { }

export class Boo implements IFoo {

  //stuff
}
```

Can I check in runtime if boo implements foo?

**Comment by bbonczek** [comment]
Ooops, didn' t noticed, that this repo is for examples only! Sorry for that!

**Comment by pcan** [comment]
No problem. Of course you can do this by checking if the interface `members` property is null or empty.
